<?
/**

	Uretici..........: Moka 
	Yazılımın Adı....: Moka_Payment // moka.com için Magento Tahsilat Modülü
	Geliştiren.......: Hidayet Ok <hidayet@grinet.com.tr>
	Web..............: https://www.moka.com/

	/// Yasal Uyarı /////////////////////////////////////////////////////////////////////////

	Tüm hakları MOKA ÖDEME KURULUŞU A.Ş.'ne aittir.

*/

$curr_codes_numeric=array(
							"104" => 	array("country" => "MYANMAR","curr_name" => "Kyat","curr_code" => "MMK"),
							"108" => 	array("country" => "BURUNDI","curr_name" => "Burundi Franc","curr_code" => "BIF"),
							"116" => 	array("country" => "CAMBODIA","curr_name" => "Riel","curr_code" => "KHR"),
							"12" => 	array("country" => "ALGERIA","curr_name" => "Algerian Dinar","curr_code" => "DZD"),
							"124" => 	array("country" => "CANADA","curr_name" => "Canadian Dollar","curr_code" => "CAD"),
							"132" => 	array("country" => "CAPE VERDE","curr_name" => "Cape Verde Escudo","curr_code" => "CVE"),
							"136" => 	array("country" => "CAYMAN ISLANDS","curr_name" => "Cayman Islands Dollar","curr_code" => "KYD"),
							"144" => 	array("country" => "SRI LANKA","curr_name" => "Sri Lanka Rupee","curr_code" => "LKR"),
							"152" => 	array("country" => "CHILE","curr_name" => "Chilean Peso","curr_code" => "CLP"),
							"156" => 	array("country" => "CHINA","curr_name" => "Yuan Renminbi","curr_code" => "CNY"),
							"170" => 	array("country" => "COLOMBIA","curr_name" => "Colombian Peso","curr_code" => "COP"),
							"174" => 	array("country" => "COMOROS","curr_name" => "Comoro Franc","curr_code" => "KMF"),
							"188" => 	array("country" => "COSTA RICA","curr_name" => "Costa Rican Colon","curr_code" => "CRC"),
							"191" => 	array("country" => "CROATIA","curr_name" => "Croatian Kuna","curr_code" => "HRK"),
							"192" => 	array("country" => "CUBA","curr_name" => "Cuban Peso","curr_code" => "CUP"),
							"203" => 	array("country" => "CZECH REPUBLIC","curr_name" => "Czech Koruna","curr_code" => "CZK"),
							"208" => 	array("country" => "DENMARK","curr_name" => "Danish Krone","curr_code" => "DKK"),
							"208" => 	array("country" => "FAROE ISLANDS","curr_name" => "Danish Krone","curr_code" => "DKK"),
							"208" => 	array("country" => "GREENLAND","curr_name" => "Danish Krone","curr_code" => "DKK"),
							"214" => 	array("country" => "DOMINICAN REPUBLIC","curr_name" => "Dominican Peso","curr_code" => "DOP"),
							"222" => 	array("country" => "EL SALVADOR","curr_name" => "El Salvador Colon","curr_code" => "SVC"),
							"230" => 	array("country" => "ETHIOPIA","curr_name" => "Ethiopian Birr","curr_code" => "ETB"),
							"232" => 	array("country" => "ERITREA","curr_name" => "Nakfa","curr_code" => "ERN"),
							"233" => 	array("country" => "ESTONIA","curr_name" => "Kroon","curr_code" => "EEK"),
							"238" => 	array("country" => "FALKLAND ISLANDS (MALVINAS)","curr_name" => "Falkland Islands Pound","curr_code" => "FKP"),
							"242" => 	array("country" => "FIJI","curr_name" => "Fiji Dollar","curr_code" => "FJD"),
							"262" => 	array("country" => "DJIBOUTI","curr_name" => "Djibouti Franc","curr_code" => "DJF"),
							"270" => 	array("country" => "GAMBIA","curr_name" => "Dalasi","curr_code" => "GMD"),
							"292" => 	array("country" => "GIBRALTAR","curr_name" => "Gibraltar Pound","curr_code" => "GIP"),
							"32" => 	array("country" => "ARGENTINA","curr_name" => "Argentine Peso","curr_code" => "ARS"),
							"320" => 	array("country" => "GUATEMALA","curr_name" => "Quetzal","curr_code" => "GTQ"),
							"324" => 	array("country" => "GUINEA","curr_name" => "Guinea Franc","curr_code" => "GNF"),
							"328" => 	array("country" => "GUYANA","curr_name" => "Guyana Dollar","curr_code" => "GYD"),
							"332" => 	array("country" => "HAITI","curr_name" => "Gourde","curr_code" => "HTG"),
							"340" => 	array("country" => "HONDURAS","curr_name" => "Lempira","curr_code" => "HNL"),
							"344" => 	array("country" => "HONG KONG","curr_name" => "Hong Kong Dollar","curr_code" => "HKD"),
							"348" => 	array("country" => "HUNGARY","curr_name" => "Forint","curr_code" => "HUF"),
							"352" => 	array("country" => "ICELAND","curr_name" => "Iceland Krona","curr_code" => "ISK"),
							"356" => 	array("country" => "BHUTAN","curr_name" => "Indian Rupee","curr_code" => "INR"),
							"356" => 	array("country" => "INDIA","curr_name" => "Indian Rupee","curr_code" => "INR"),
							"36" => 	array("country" => "AUSTRALIA","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"36" => 	array("country" => "CHRISTMAS ISLAND","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"36" => 	array("country" => "COCOS (KEELING) ISLANDS","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"36" => 	array("country" => "HEARD ISLAND AND MCDONALD ISLANDS","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"36" => 	array("country" => "KIRIBATI","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"36" => 	array("country" => "NAURU","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"36" => 	array("country" => "NORFOLK ISLAND","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"36" => 	array("country" => "TUVALU","curr_name" => "Australian Dollar","curr_code" => "AUD"),
							"360" => 	array("country" => "INDONESIA","curr_name" => "Rupiah","curr_code" => "IDR"),
							"364" => 	array("country" => "IRAN, ISLAMIC REPUBLIC OF","curr_name" => "Iranian Rial","curr_code" => "IRR"),
							"368" => 	array("country" => "IRAQ","curr_name" => "Iraqi Dinar","curr_code" => "IQD"),
							"376" => 	array("country" => "ISRAEL","curr_name" => "New Israeli Sheqel","curr_code" => "ILS"),
							"388" => 	array("country" => "JAMAICA","curr_name" => "Jamaican Dollar","curr_code" => "JMD"),
							"392" => 	array("country" => "JAPAN","curr_name" => "Yen","curr_code" => "JPY"),
							"398" => 	array("country" => "KAZAKHSTAN","curr_name" => "Tenge","curr_code" => "KZT"),
							"400" => 	array("country" => "JORDAN","curr_name" => "Jordanian Dinar","curr_code" => "JOD"),
							"404" => 	array("country" => "KENYA","curr_name" => "Kenyan Shilling","curr_code" => "KES"),
							"408" => 	array("country" => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF","curr_name" => "North Korean Won","curr_code" => "KPW"),
							"410" => 	array("country" => "KOREA, REPUBLIC OF","curr_name" => "Won","curr_code" => "KRW"),
							"414" => 	array("country" => "KUWAIT","curr_name" => "Kuwaiti Dinar","curr_code" => "KWD"),
							"417" => 	array("country" => "KYRGYZSTAN","curr_name" => "Som","curr_code" => "KGS"),
							"418" => 	array("country" => "LAO PEOPLE'S DEMOCRATIC REPUBLIC","curr_name" => "Kip","curr_code" => "LAK"),
							"422" => 	array("country" => "LEBANON","curr_name" => "Lebanese Pound","curr_code" => "LBP"),
							"426" => 	array("country" => "LESOTHO","curr_name" => "Loti","curr_code" => "LSL"),
							"428" => 	array("country" => "LATVIA","curr_name" => "Latvian Lats","curr_code" => "LVL"),
							"430" => 	array("country" => "LIBERIA","curr_name" => "Liberian Dollar","curr_code" => "LRD"),
							"434" => 	array("country" => "LIBYAN ARAB JAMAHIRIYA","curr_name" => "Libyan Dinar","curr_code" => "LYD"),
							"44" => 	array("country" => "BAHAMAS","curr_name" => "Bahamian Dollar","curr_code" => "BSD"),
							"440" => 	array("country" => "LITHUANIA","curr_name" => "Lithuanian Litas","curr_code" => "LTL"),
							"446" => 	array("country" => "MACAO","curr_name" => "Pataca","curr_code" => "MOP"),
							"454" => 	array("country" => "MALAWI","curr_name" => "Kwacha","curr_code" => "MWK"),
							"458" => 	array("country" => "MALAYSIA","curr_name" => "Malaysian Ringgit","curr_code" => "MYR"),
							"462" => 	array("country" => "MALDIVES","curr_name" => "Rufiyaa","curr_code" => "MVR"),
							"478" => 	array("country" => "MAURITANIA","curr_name" => "Ouguiya","curr_code" => "MRO"),
							"48" => 	array("country" => "BAHRAIN","curr_name" => "Bahraini Dinar","curr_code" => "BHD"),
							"480" => 	array("country" => "MAURITIUS","curr_name" => "Mauritius Rupee","curr_code" => "MUR"),
							"484" => 	array("country" => "MEXICO","curr_name" => "Mexican Peso","curr_code" => "MXN"),
							"496" => 	array("country" => "MONGOLIA","curr_name" => "Tugrik","curr_code" => "MNT"),
							"498" => 	array("country" => "MOLDOVA, REPUBLIC OF","curr_name" => "Moldovan Leu","curr_code" => "MDL"),
							"50" => 	array("country" => "BANGLADESH","curr_name" => "Taka","curr_code" => "BDT"),
							"504" => 	array("country" => "MOROCCO","curr_name" => "Moroccan Dirham","curr_code" => "MAD"),
							"504" => 	array("country" => "WESTERN SAHARA","curr_name" => "Moroccan Dirham","curr_code" => "MAD"),
							"51" => 	array("country" => "ARMENIA","curr_name" => "Armenian Dram","curr_code" => "AMD"),
							"512" => 	array("country" => "OMAN","curr_name" => "Rial Omani","curr_code" => "OMR"),
							"516" => 	array("country" => "NAMIBIA","curr_name" => "Namibia Dollar","curr_code" => "NAD"),
							"52" => 	array("country" => "BARBADOS","curr_name" => "Barbados Dollar","curr_code" => "BBD"),
							"524" => 	array("country" => "NEPAL","curr_name" => "Nepalese Rupee","curr_code" => "NPR"),
							"532" => 	array("country" => "NETHERLANDS ANTILLES","curr_name" => "Netherlands Antillian Guilder","curr_code" => "ANG"),
							"533" => 	array("country" => "ARUBA","curr_name" => "Aruban Guilder","curr_code" => "AWG"),
							"548" => 	array("country" => "VANUATU","curr_name" => "Vatu","curr_code" => "VUV"),
							"554" => 	array("country" => "COOK ISLANDS","curr_name" => "New Zealand Dollar","curr_code" => "NZD"),
							"554" => 	array("country" => "NEW ZEALAND","curr_name" => "New Zealand Dollar","curr_code" => "NZD"),
							"554" => 	array("country" => "NIUE","curr_name" => "New Zealand Dollar","curr_code" => "NZD"),
							"554" => 	array("country" => "PITCAIRN","curr_name" => "New Zealand Dollar","curr_code" => "NZD"),
							"554" => 	array("country" => "TOKELAU","curr_name" => "New Zealand Dollar","curr_code" => "NZD"),
							"558" => 	array("country" => "NICARAGUA","curr_name" => "Cordoba Oro","curr_code" => "NIO"),
							"566" => 	array("country" => "NIGERIA","curr_name" => "Naira","curr_code" => "NGN"),
							"578" => 	array("country" => "BOUVET ISLAND","curr_name" => "Norwegian Krone","curr_code" => "NOK"),
							"578" => 	array("country" => "NORWAY","curr_name" => "Norwegian Krone","curr_code" => "NOK"),
							"578" => 	array("country" => "SVALBARD AND JAN MAYEN","curr_name" => "Norwegian Krone","curr_code" => "NOK"),
							"586" => 	array("country" => "PAKISTAN","curr_name" => "Pakistan Rupee","curr_code" => "PKR"),
							"590" => 	array("country" => "PANAMA","curr_name" => "Balboa","curr_code" => "PAB"),
							"598" => 	array("country" => "PAPUA NEW GUINEA","curr_name" => "Kina","curr_code" => "PGK"),
							"60" => 	array("country" => "BERMUDA","curr_name" => "Bermudian Dollar ","curr_code" => "BMD"),
							"600" => 	array("country" => "PARAGUAY","curr_name" => "Guarani","curr_code" => "PYG"),
							"604" => 	array("country" => "PERU","curr_name" => "Nuevo Sol","curr_code" => "PEN"),
							"608" => 	array("country" => "PHILIPPINES","curr_name" => "Philippine Peso","curr_code" => "PHP"),
							"624" => 	array("country" => "GUINEA-BISSAU","curr_name" => "Guinea-Bissau Peso","curr_code" => "GWP"),
							"634" => 	array("country" => "QATAR","curr_name" => "Qatari Rial","curr_code" => "QAR"),
							"643" => 	array("country" => "RUSSIAN FEDERATION","curr_name" => "Russian Ruble","curr_code" => "RUB"),
							"646" => 	array("country" => "RWANDA","curr_name" => "Rwanda Franc","curr_code" => "RWF"),
							"654" => 	array("country" => "SAINT HELENA","curr_name" => "Saint Helena Pound","curr_code" => "SHP"),
							"678" => 	array("country" => "SÃO TOME AND PRINCIPE","curr_name" => "Dobra","curr_code" => "STD"),
							"68" => 	array("country" => "BOLIVIA","curr_name" => "Boliviano","curr_code" => "BOB"),
							"682" => 	array("country" => "SAUDI ARABIA","curr_name" => "Saudi Riyal","curr_code" => "SAR"),
							"690" => 	array("country" => "SEYCHELLES","curr_name" => "Seychelles Rupee","curr_code" => "SCR"),
							"694" => 	array("country" => "SIERRA LEONE","curr_name" => "Leone","curr_code" => "SLL"),
							"702" => 	array("country" => "SINGAPORE","curr_name" => "Singapore Dollar","curr_code" => "SGD"),
							"704" => 	array("country" => "VIET NAM","curr_name" => "Dong","curr_code" => "VND"),
							"706" => 	array("country" => "SOMALIA","curr_name" => "Somali Shilling","curr_code" => "SOS"),
							"710" => 	array("country" => "LESOTHO","curr_name" => "Rand","curr_code" => "ZAR"),
							"710" => 	array("country" => "NAMIBIA","curr_name" => "Rand","curr_code" => "ZAR"),
							"710" => 	array("country" => "SOUTH AFRICA","curr_name" => "Rand","curr_code" => "ZAR"),
							"72" => 	array("country" => "BOTSWANA","curr_name" => "Pula","curr_code" => "BWP"),
							"748" => 	array("country" => "SWAZILAND","curr_name" => "Lilangeni","curr_code" => "SZL"),
							"752" => 	array("country" => "SWEDEN","curr_name" => "Swedish Krona","curr_code" => "SEK"),
							"756" => 	array("country" => "LIECHTENSTEIN","curr_name" => "Swiss Franc","curr_code" => "CHF"),
							"756" => 	array("country" => "SWITZERLAND","curr_name" => "Swiss Franc","curr_code" => "CHF"),
							"760" => 	array("country" => "SYRIAN ARAB REPUBLIC","curr_name" => "Syrian Pound","curr_code" => "SYP"),
							"764" => 	array("country" => "THAILAND","curr_name" => "Baht","curr_code" => "THB"),
							"776" => 	array("country" => "TONGA","curr_name" => "Pa'anga","curr_code" => "TOP"),
							"780" => 	array("country" => "TRINIDAD AND TOBAGO","curr_name" => "Trinidad and Tobago Dollar","curr_code" => "TTD"),
							"784" => 	array("country" => "UNITED ARAB EMIRATES","curr_name" => "UAE Dirham","curr_code" => "AED"),
							"788" => 	array("country" => "TUNISIA","curr_name" => "Tunisian Dinar","curr_code" => "TND"),
							"8" => 		array("country" => "ALBANIA","curr_name" => "Lek","curr_code" => "ALL"),
							"800" => 	array("country" => "UGANDA","curr_name" => "Uganda Shilling","curr_code" => "UGX"),
							"807" => 	array("country" => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF","curr_name" => "Denar","curr_code" => "MKD"),
							"818" => 	array("country" => "EGYPT","curr_name" => "Egyptian Pound","curr_code" => "EGP"),
							"826" => 	array("country" => "GUERNSEY","curr_name" => "Pound Sterling","curr_code" => "GBP"),
							"826" => 	array("country" => "JERSEY","curr_name" => "Pound Sterling","curr_code" => "GBP"),
							"826" => 	array("country" => "UNITED KINGDOM","curr_name" => "Pound Sterling","curr_code" => "GBP"),
							"834" => 	array("country" => "TANZANIA, UNITED REPUBLIC OF","curr_name" => "Tanzanian Shilling","curr_code" => "TZS"),
							"84" => 	array("country" => "BELIZE","curr_name" => "Belize Dollar","curr_code" => "BZD"),
							"840" => 	array("country" => "UNITED STATES","curr_name" => "US Dollar","curr_code" => "USD"),
							"858" => 	array("country" => "URUGUAY","curr_name" => "Peso Uruguayo","curr_code" => "UYU"),
							"860" => 	array("country" => "UZBEKISTAN","curr_name" => "Uzbekistan Sum","curr_code" => "UZS"),
							"882" => 	array("country" => "SAMOA","curr_name" => "Tala","curr_code" => "WST"),
							"886" => 	array("country" => "YEMEN","curr_name" => "Yemeni Rial","curr_code" => "YER"),
							"894" => 	array("country" => "ZAMBIA","curr_name" => "Zambian Kwacha","curr_code" => "ZMK"),
							"90" => 	array("country" => "SOLOMON ISLANDS","curr_name" => "Solomon Islands Dollar","curr_code" => "SBD"),
							"901" => 	array("country" => "TAIWAN, PROVINCE OF CHINA","curr_name" => "New Taiwan Dollar","curr_code" => "TWD"),
							"934" => 	array("country" => "TURKMENISTAN","curr_name" => "Manat","curr_code" => "TMT"),
							"935" => 	array("country" => "ZIMBABWE","curr_name" => "Zimbabwe Dollar","curr_code" => "ZWR"),
							"936" => 	array("country" => "GHANA","curr_name" => "Cedi","curr_code" => "GHS"),
							"937" => 	array("country" => "VENEZUELA","curr_name" => "Bolivar Fuerte","curr_code" => "VEF"),
							"938" => 	array("country" => "SUDAN","curr_name" => "Sudanese Pound","curr_code" => "SDG"),
							"940" => 	array("country" => "URUGUAY","curr_name" => "Uruguay Peso en Unidades Indexadas","curr_code" => "UYI"),
							"941" => 	array("country" => "SERBIA","curr_name" => "Serbian Dinar","curr_code" => "RSD"),
							"943" => 	array("country" => "MOZAMBIQUE","curr_name" => "Metical","curr_code" => "MZN"),
							"944" => 	array("country" => "AZERBAIJAN","curr_name" => "Azerbaijanian Manat","curr_code" => "AZN"),
							"946" => 	array("country" => "ROMANIA","curr_name" => "New Leu","curr_code" => "RON"),
							"947" => 	array("country" => "SWITZERLAND","curr_name" => "WIR Euro","curr_code" => "CHE"),
							"948" => 	array("country" => "SWITZERLAND","curr_name" => "WIR Franc","curr_code" => "CHW"),
							"949" => 	array("country" => "TURKEY","curr_name" => "Turkish Lira","curr_code" => "TRL"),
							"949" => 	array("country" => "TURKEY","curr_name" => "Turkish Lira","curr_code" => "TRY"),
							"950" => 	array("country" => "CAMEROON","curr_name" => "CFA Franc BEAC ","curr_code" => "XAF"),
							"950" => 	array("country" => "CENTRAL AFRICAN REPUBLIC","curr_name" => "CFA Franc BEAC ","curr_code" => "XAF"),
							"950" => 	array("country" => "CHAD","curr_name" => "CFA Franc BEAC ","curr_code" => "XAF"),
							"950" => 	array("country" => "CONGO","curr_name" => "CFA Franc BEAC ","curr_code" => "XAF"),
							"950" => 	array("country" => "EQUATORIAL GUINEA","curr_name" => "CFA Franc BEAC ","curr_code" => "XAF"),
							"950" => 	array("country" => "GABON","curr_name" => "CFA Franc BEAC ","curr_code" => "XAF"),
							"951" => 	array("country" => "ANGUILLA","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"951" => 	array("country" => "ANTIGUA AND BARBUDA","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"951" => 	array("country" => "DOMINICA","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"951" => 	array("country" => "GRENADA","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"951" => 	array("country" => "MONTSERRAT","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"951" => 	array("country" => "SAINT KITTS AND NEVIS","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"951" => 	array("country" => "SAINT LUCIA","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"951" => 	array("country" => "SAINT VINCENT AND THE GRENADINES","curr_name" => "East Caribbean Dollar","curr_code" => "XCD"),
							"952" => 	array("country" => "BENIN","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"952" => 	array("country" => "BURKINA FASO","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"952" => 	array("country" => "CÔTE D'IVOIRE","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"952" => 	array("country" => "GUINEA-BISSAU","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"952" => 	array("country" => "MALI","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"952" => 	array("country" => "NIGER","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"952" => 	array("country" => "SENEGAL","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"952" => 	array("country" => "TOGO","curr_name" => "CFA Franc BCEAO ","curr_code" => "XOF"),
							"953" => 	array("country" => "FRENCH POLYNESIA","curr_name" => "CFP Franc","curr_code" => "XPF"),
							"953" => 	array("country" => "NEW CALEDONIA","curr_name" => "CFP Franc","curr_code" => "XPF"),
							"953" => 	array("country" => "WALLIS AND FUTUNA","curr_name" => "CFP Franc","curr_code" => "XPF"),
							"96" => 	array("country" => "BRUNEI DARUSSALAM","curr_name" => "Brunei Dollar","curr_code" => "BND"),
							"968" => 	array("country" => "SURINAME","curr_name" => "Surinam Dollar","curr_code" => "SRD"),
							"969" => 	array("country" => "MADAGASCAR","curr_name" => "Malagasy Ariary","curr_code" => "MGA"),
							"970" => 	array("country" => "COLOMBIA","curr_name" => "Unidad de Valor Real","curr_code" => "COU"),
							"971" => 	array("country" => "AFGHANISTAN","curr_name" => "Afghani","curr_code" => "AFN"),
							"972" => 	array("country" => "TAJIKISTAN","curr_name" => "Somoni","curr_code" => "TJS"),
							"973" => 	array("country" => "ANGOLA","curr_name" => "Kwanza","curr_code" => "AOA"),
							"974" => 	array("country" => "BELARUS","curr_name" => "Belarussian Ruble","curr_code" => "BYR"),
							"975" => 	array("country" => "BULGARIA","curr_name" => "Bulgarian Lev","curr_code" => "BGN"),
							"976" => 	array("country" => "CONGO, THE DEMOCRATIC REPUBLIC OF","curr_name" => "Congolese Franc","curr_code" => "CDF"),
							"977" => 	array("country" => "BOSNIA AND HERZEGOVINA","curr_name" => "Convertible Marks","curr_code" => "BAM"),
							"978" => 	array("country" => "EUROPEAN UNION","curr_name" => "Euro","curr_code" => "EUR"),
							"979" => 	array("country" => "MEXICO","curr_name" => "Mexican Unidad de Inversion (UDI)","curr_code" => "MXV"),
							"980" => 	array("country" => "UKRAINE","curr_name" => "Hryvnia","curr_code" => "UAH"),
							"981" => 	array("country" => "GEORGIA","curr_name" => "Lari","curr_code" => "GEL"),
							"984" => 	array("country" => "BOLIVIA","curr_name" => "Mvdol","curr_code" => "BOV"),
							"985" => 	array("country" => "POLAND","curr_name" => "Zloty","curr_code" => "PLN"),
							"986" => 	array("country" => "BRAZIL","curr_name" => "Brazilian Real","curr_code" => "BRL"),
							"990" => 	array("country" => "CHILE","curr_name" => "Unidades de fomento","curr_code" => "CLF"),
							"997" => 	array("country" => "UNITED STATES","curr_name" => "US Dollar (Next day)","curr_code" => "USN"),
							"998" => 	array("country" => "UNITED STATES","curr_name" => "US Dollar (Same day)","curr_code" => "USS"),
							);

$curr_codes=array(
							"AED" => array("country" => "UNITED ARAB EMIRATES","curr_name" => "UAE Dirham","curr_number" => "784"),
							"AFN" => array("country" => "AFGHANISTAN","curr_name" => "Afghani","curr_number" => "971"),
							"ALL" => array("country" => "ALBANIA","curr_name" => "Lek","curr_number" => "8"),
							"AMD" => array("country" => "ARMENIA","curr_name" => "Armenian Dram","curr_number" => "51"),
							"ANG" => array("country" => "NETHERLANDS ANTILLES","curr_name" => "Netherlands Antillian Guilder","curr_number" => "532"),
							"AOA" => array("country" => "ANGOLA","curr_name" => "Kwanza","curr_number" => "973"),
							"ARS" => array("country" => "ARGENTINA","curr_name" => "Argentine Peso","curr_number" => "32"),
							"AUD" => array("country" => "AUSTRALIA","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AUD" => array("country" => "CHRISTMAS ISLAND","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AUD" => array("country" => "COCOS (KEELING) ISLANDS","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AUD" => array("country" => "HEARD ISLAND AND MCDONALD ISLANDS","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AUD" => array("country" => "KIRIBATI","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AUD" => array("country" => "NAURU","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AUD" => array("country" => "NORFOLK ISLAND","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AUD" => array("country" => "TUVALU","curr_name" => "Australian Dollar","curr_number" => "36"),
							"AWG" => array("country" => "ARUBA","curr_name" => "Aruban Guilder","curr_number" => "533"),
							"AZN" => array("country" => "AZERBAIJAN","curr_name" => "Azerbaijanian Manat","curr_number" => "944"),
							"BAM" => array("country" => "BOSNIA AND HERZEGOVINA","curr_name" => "Convertible Marks","curr_number" => "977"),
							"BBD" => array("country" => "BARBADOS","curr_name" => "Barbados Dollar","curr_number" => "52"),
							"BDT" => array("country" => "BANGLADESH","curr_name" => "Taka","curr_number" => "50"),
							"BGN" => array("country" => "BULGARIA","curr_name" => "Bulgarian Lev","curr_number" => "975"),
							"BHD" => array("country" => "BAHRAIN","curr_name" => "Bahraini Dinar","curr_number" => "48"),
							"BIF" => array("country" => "BURUNDI","curr_name" => "Burundi Franc","curr_number" => "108"),
							"BMD" => array("country" => "BERMUDA","curr_name" => "Bermudian Dollar ","curr_number" => "60"),
							"BND" => array("country" => "BRUNEI DARUSSALAM","curr_name" => "Brunei Dollar","curr_number" => "96"),
							"BOB" => array("country" => "BOLIVIA","curr_name" => "Boliviano","curr_number" => "68"),
							"BOV" => array("country" => "BOLIVIA","curr_name" => "Mvdol","curr_number" => "984"),
							"BRL" => array("country" => "BRAZIL","curr_name" => "Brazilian Real","curr_number" => "986"),
							"BSD" => array("country" => "BAHAMAS","curr_name" => "Bahamian Dollar","curr_number" => "44"),
							"BWP" => array("country" => "BOTSWANA","curr_name" => "Pula","curr_number" => "72"),
							"BYR" => array("country" => "BELARUS","curr_name" => "Belarussian Ruble","curr_number" => "974"),
							"BZD" => array("country" => "BELIZE","curr_name" => "Belize Dollar","curr_number" => "84"),
							"CAD" => array("country" => "CANADA","curr_name" => "Canadian Dollar","curr_number" => "124"),
							"CDF" => array("country" => "CONGO, THE DEMOCRATIC REPUBLIC OF","curr_name" => "Congolese Franc","curr_number" => "976"),
							"CHE" => array("country" => "SWITZERLAND","curr_name" => "WIR Euro","curr_number" => "947"),
							"CHF" => array("country" => "LIECHTENSTEIN","curr_name" => "Swiss Franc","curr_number" => "756"),
							"CHF" => array("country" => "SWITZERLAND","curr_name" => "Swiss Franc","curr_number" => "756"),
							"CHW" => array("country" => "SWITZERLAND","curr_name" => "WIR Franc","curr_number" => "948"),
							"CLF" => array("country" => "CHILE","curr_name" => "Unidades de fomento","curr_number" => "990"),
							"CLP" => array("country" => "CHILE","curr_name" => "Chilean Peso","curr_number" => "152"),
							"CNY" => array("country" => "CHINA","curr_name" => "Yuan Renminbi","curr_number" => "156"),
							"COP" => array("country" => "COLOMBIA","curr_name" => "Colombian Peso","curr_number" => "170"),
							"COU" => array("country" => "COLOMBIA","curr_name" => "Unidad de Valor Real","curr_number" => "970"),
							"CRC" => array("country" => "COSTA RICA","curr_name" => "Costa Rican Colon","curr_number" => "188"),
							"CUP" => array("country" => "CUBA","curr_name" => "Cuban Peso","curr_number" => "192"),
							"CVE" => array("country" => "CAPE VERDE","curr_name" => "Cape Verde Escudo","curr_number" => "132"),
							"CZK" => array("country" => "CZECH REPUBLIC","curr_name" => "Czech Koruna","curr_number" => "203"),
							"DJF" => array("country" => "DJIBOUTI","curr_name" => "Djibouti Franc","curr_number" => "262"),
							"DKK" => array("country" => "DENMARK","curr_name" => "Danish Krone","curr_number" => "208"),
							"DKK" => array("country" => "FAROE ISLANDS","curr_name" => "Danish Krone","curr_number" => "208"),
							"DKK" => array("country" => "GREENLAND","curr_name" => "Danish Krone","curr_number" => "208"),
							"DOP" => array("country" => "DOMINICAN REPUBLIC","curr_name" => "Dominican Peso","curr_number" => "214"),
							"DZD" => array("country" => "ALGERIA","curr_name" => "Algerian Dinar","curr_number" => "12"),
							"EEK" => array("country" => "ESTONIA","curr_name" => "Kroon","curr_number" => "233"),
							"EGP" => array("country" => "EGYPT","curr_name" => "Egyptian Pound","curr_number" => "818"),
							"ERN" => array("country" => "ERITREA","curr_name" => "Nakfa","curr_number" => "232"),
							"ETB" => array("country" => "ETHIOPIA","curr_name" => "Ethiopian Birr","curr_number" => "230"),
							"EUR" => array("country" => "ANDORRA","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "AUSTRIA","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "BELGIUM","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "CYPRUS","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "FINLAND","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "FRANCE","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "FRENCH GUIANA","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "FRENCH SOUTHERN TERRITORIES","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "GERMANY","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "GREECE","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "GUADELOUPE","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "HOLY SEE (VATICAN CITY STATE)","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "IRELAND","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "ITALY","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "LUXEMBOURG","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "MALTA","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "MARTINIQUE","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "MAYOTTE","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "MONACO","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "MONTENEGRO","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "NETHERLANDS","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "PORTUGAL","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "RÉUNION","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "SAINT MARTIN","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "SAINT PIERRE AND MIQUELON","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "SAINT-BARTHÉLEMY","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "SAN MARINO","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "SLOVAKIA","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "SLOVENIA","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "SPAIN","curr_name" => "Euro","curr_number" => "978"),
							"EUR" => array("country" => "ÅLAND ISLANDS","curr_name" => "Euro","curr_number" => "978"),
							"FJD" => array("country" => "FIJI","curr_name" => "Fiji Dollar","curr_number" => "242"),
							"FKP" => array("country" => "FALKLAND ISLANDS (MALVINAS)","curr_name" => "Falkland Islands Pound","curr_number" => "238"),
							"GBP" => array("country" => "GUERNSEY","curr_name" => "Pound Sterling","curr_number" => "826"),
							"GBP" => array("country" => "JERSEY","curr_name" => "Pound Sterling","curr_number" => "826"),
							"GBP" => array("country" => "UNITED KINGDOM","curr_name" => "Pound Sterling","curr_number" => "826"),
							"GEL" => array("country" => "GEORGIA","curr_name" => "Lari","curr_number" => "981"),
							"GHS" => array("country" => "GHANA","curr_name" => "Cedi","curr_number" => "936"),
							"GIP" => array("country" => "GIBRALTAR","curr_name" => "Gibraltar Pound","curr_number" => "292"),
							"GMD" => array("country" => "GAMBIA","curr_name" => "Dalasi","curr_number" => "270"),
							"GNF" => array("country" => "GUINEA","curr_name" => "Guinea Franc","curr_number" => "324"),
							"GTQ" => array("country" => "GUATEMALA","curr_name" => "Quetzal","curr_number" => "320"),
							"GWP" => array("country" => "GUINEA-BISSAU","curr_name" => "Guinea-Bissau Peso","curr_number" => "624"),
							"GYD" => array("country" => "GUYANA","curr_name" => "Guyana Dollar","curr_number" => "328"),
							"HKD" => array("country" => "HONG KONG","curr_name" => "Hong Kong Dollar","curr_number" => "344"),
							"HNL" => array("country" => "HONDURAS","curr_name" => "Lempira","curr_number" => "340"),
							"HRK" => array("country" => "CROATIA","curr_name" => "Croatian Kuna","curr_number" => "191"),
							"HTG" => array("country" => "HAITI","curr_name" => "Gourde","curr_number" => "332"),
							"HUF" => array("country" => "HUNGARY","curr_name" => "Forint","curr_number" => "348"),
							"IDR" => array("country" => "INDONESIA","curr_name" => "Rupiah","curr_number" => "360"),
							"ILS" => array("country" => "ISRAEL","curr_name" => "New Israeli Sheqel","curr_number" => "376"),
							"INR" => array("country" => "BHUTAN","curr_name" => "Indian Rupee","curr_number" => "356"),
							"INR" => array("country" => "INDIA","curr_name" => "Indian Rupee","curr_number" => "356"),
							"IQD" => array("country" => "IRAQ","curr_name" => "Iraqi Dinar","curr_number" => "368"),
							"IRR" => array("country" => "IRAN, ISLAMIC REPUBLIC OF","curr_name" => "Iranian Rial","curr_number" => "364"),
							"ISK" => array("country" => "ICELAND","curr_name" => "Iceland Krona","curr_number" => "352"),
							"JMD" => array("country" => "JAMAICA","curr_name" => "Jamaican Dollar","curr_number" => "388"),
							"JOD" => array("country" => "JORDAN","curr_name" => "Jordanian Dinar","curr_number" => "400"),
							"JPY" => array("country" => "JAPAN","curr_name" => "Yen","curr_number" => "392"),
							"KES" => array("country" => "KENYA","curr_name" => "Kenyan Shilling","curr_number" => "404"),
							"KGS" => array("country" => "KYRGYZSTAN","curr_name" => "Som","curr_number" => "417"),
							"KHR" => array("country" => "CAMBODIA","curr_name" => "Riel","curr_number" => "116"),
							"KMF" => array("country" => "COMOROS","curr_name" => "Comoro Franc","curr_number" => "174"),
							"KPW" => array("country" => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF","curr_name" => "North Korean Won","curr_number" => "408"),
							"KRW" => array("country" => "KOREA, REPUBLIC OF","curr_name" => "Won","curr_number" => "410"),
							"KWD" => array("country" => "KUWAIT","curr_name" => "Kuwaiti Dinar","curr_number" => "414"),
							"KYD" => array("country" => "CAYMAN ISLANDS","curr_name" => "Cayman Islands Dollar","curr_number" => "136"),
							"KZT" => array("country" => "KAZAKHSTAN","curr_name" => "Tenge","curr_number" => "398"),
							"LAK" => array("country" => "LAO PEOPLE'S DEMOCRATIC REPUBLIC","curr_name" => "Kip","curr_number" => "418"),
							"LBP" => array("country" => "LEBANON","curr_name" => "Lebanese Pound","curr_number" => "422"),
							"LKR" => array("country" => "SRI LANKA","curr_name" => "Sri Lanka Rupee","curr_number" => "144"),
							"LRD" => array("country" => "LIBERIA","curr_name" => "Liberian Dollar","curr_number" => "430"),
							"LSL" => array("country" => "LESOTHO","curr_name" => "Loti","curr_number" => "426"),
							"LTL" => array("country" => "LITHUANIA","curr_name" => "Lithuanian Litas","curr_number" => "440"),
							"LVL" => array("country" => "LATVIA","curr_name" => "Latvian Lats","curr_number" => "428"),
							"LYD" => array("country" => "LIBYAN ARAB JAMAHIRIYA","curr_name" => "Libyan Dinar","curr_number" => "434"),
							"MAD" => array("country" => "MOROCCO","curr_name" => "Moroccan Dirham","curr_number" => "504"),
							"MAD" => array("country" => "WESTERN SAHARA","curr_name" => "Moroccan Dirham","curr_number" => "504"),
							"MDL" => array("country" => "MOLDOVA, REPUBLIC OF","curr_name" => "Moldovan Leu","curr_number" => "498"),
							"MGA" => array("country" => "MADAGASCAR","curr_name" => "Malagasy Ariary","curr_number" => "969"),
							"MKD" => array("country" => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF","curr_name" => "Denar","curr_number" => "807"),
							"MMK" => array("country" => "MYANMAR","curr_name" => "Kyat","curr_number" => "104"),
							"MNT" => array("country" => "MONGOLIA","curr_name" => "Tugrik","curr_number" => "496"),
							"MOP" => array("country" => "MACAO","curr_name" => "Pataca","curr_number" => "446"),
							"MRO" => array("country" => "MAURITANIA","curr_name" => "Ouguiya","curr_number" => "478"),
							"MUR" => array("country" => "MAURITIUS","curr_name" => "Mauritius Rupee","curr_number" => "480"),
							"MVR" => array("country" => "MALDIVES","curr_name" => "Rufiyaa","curr_number" => "462"),
							"MWK" => array("country" => "MALAWI","curr_name" => "Kwacha","curr_number" => "454"),
							"MXN" => array("country" => "MEXICO","curr_name" => "Mexican Peso","curr_number" => "484"),
							"MXV" => array("country" => "MEXICO","curr_name" => "Mexican Unidad de Inversion (UDI)","curr_number" => "979"),
							"MYR" => array("country" => "MALAYSIA","curr_name" => "Malaysian Ringgit","curr_number" => "458"),
							"MZN" => array("country" => "MOZAMBIQUE","curr_name" => "Metical","curr_number" => "943"),
							"NAD" => array("country" => "NAMIBIA","curr_name" => "Namibia Dollar","curr_number" => "516"),
							"NGN" => array("country" => "NIGERIA","curr_name" => "Naira","curr_number" => "566"),
							"NIO" => array("country" => "NICARAGUA","curr_name" => "Cordoba Oro","curr_number" => "558"),
							"NOK" => array("country" => "BOUVET ISLAND","curr_name" => "Norwegian Krone","curr_number" => "578"),
							"NOK" => array("country" => "NORWAY","curr_name" => "Norwegian Krone","curr_number" => "578"),
							"NOK" => array("country" => "SVALBARD AND JAN MAYEN","curr_name" => "Norwegian Krone","curr_number" => "578"),
							"NPR" => array("country" => "NEPAL","curr_name" => "Nepalese Rupee","curr_number" => "524"),
							"NZD" => array("country" => "COOK ISLANDS","curr_name" => "New Zealand Dollar","curr_number" => "554"),
							"NZD" => array("country" => "NEW ZEALAND","curr_name" => "New Zealand Dollar","curr_number" => "554"),
							"NZD" => array("country" => "NIUE","curr_name" => "New Zealand Dollar","curr_number" => "554"),
							"NZD" => array("country" => "PITCAIRN","curr_name" => "New Zealand Dollar","curr_number" => "554"),
							"NZD" => array("country" => "TOKELAU","curr_name" => "New Zealand Dollar","curr_number" => "554"),
							"OMR" => array("country" => "OMAN","curr_name" => "Rial Omani","curr_number" => "512"),
							"PAB" => array("country" => "PANAMA","curr_name" => "Balboa","curr_number" => "590"),
							"PEN" => array("country" => "PERU","curr_name" => "Nuevo Sol","curr_number" => "604"),
							"PGK" => array("country" => "PAPUA NEW GUINEA","curr_name" => "Kina","curr_number" => "598"),
							"PHP" => array("country" => "PHILIPPINES","curr_name" => "Philippine Peso","curr_number" => "608"),
							"PKR" => array("country" => "PAKISTAN","curr_name" => "Pakistan Rupee","curr_number" => "586"),
							"PLN" => array("country" => "POLAND","curr_name" => "Zloty","curr_number" => "985"),
							"PYG" => array("country" => "PARAGUAY","curr_name" => "Guarani","curr_number" => "600"),
							"QAR" => array("country" => "QATAR","curr_name" => "Qatari Rial","curr_number" => "634"),
							"RON" => array("country" => "ROMANIA","curr_name" => "New Leu","curr_number" => "946"),
							"RSD" => array("country" => "SERBIA","curr_name" => "Serbian Dinar","curr_number" => "941"),
							"RUB" => array("country" => "RUSSIAN FEDERATION","curr_name" => "Russian Ruble","curr_number" => "643"),
							"RWF" => array("country" => "RWANDA","curr_name" => "Rwanda Franc","curr_number" => "646"),
							"SAR" => array("country" => "SAUDI ARABIA","curr_name" => "Saudi Riyal","curr_number" => "682"),
							"SBD" => array("country" => "SOLOMON ISLANDS","curr_name" => "Solomon Islands Dollar","curr_number" => "90"),
							"SCR" => array("country" => "SEYCHELLES","curr_name" => "Seychelles Rupee","curr_number" => "690"),
							"SDG" => array("country" => "SUDAN","curr_name" => "Sudanese Pound","curr_number" => "938"),
							"SEK" => array("country" => "SWEDEN","curr_name" => "Swedish Krona","curr_number" => "752"),
							"SGD" => array("country" => "SINGAPORE","curr_name" => "Singapore Dollar","curr_number" => "702"),
							"SHP" => array("country" => "SAINT HELENA","curr_name" => "Saint Helena Pound","curr_number" => "654"),
							"SLL" => array("country" => "SIERRA LEONE","curr_name" => "Leone","curr_number" => "694"),
							"SOS" => array("country" => "SOMALIA","curr_name" => "Somali Shilling","curr_number" => "706"),
							"SRD" => array("country" => "SURINAME","curr_name" => "Surinam Dollar","curr_number" => "968"),
							"STD" => array("country" => "SÃO TOME AND PRINCIPE","curr_name" => "Dobra","curr_number" => "678"),
							"SVC" => array("country" => "EL SALVADOR","curr_name" => "El Salvador Colon","curr_number" => "222"),
							"SYP" => array("country" => "SYRIAN ARAB REPUBLIC","curr_name" => "Syrian Pound","curr_number" => "760"),
							"SZL" => array("country" => "SWAZILAND","curr_name" => "Lilangeni","curr_number" => "748"),
							"THB" => array("country" => "THAILAND","curr_name" => "Baht","curr_number" => "764"),
							"TJS" => array("country" => "TAJIKISTAN","curr_name" => "Somoni","curr_number" => "972"),
							"TMT" => array("country" => "TURKMENISTAN","curr_name" => "Manat","curr_number" => "934"),
							"TND" => array("country" => "TUNISIA","curr_name" => "Tunisian Dinar","curr_number" => "788"),
							"TOP" => array("country" => "TONGA","curr_name" => "Pa'anga","curr_number" => "776"),
							"TRL" => array("country" => "TURKEY","curr_name" => "Turkish Lira","curr_number" => "949"),
							"TRY" => array("country" => "TURKEY","curr_name" => "Turkish Lira","curr_number" => "949"),
							"TTD" => array("country" => "TRINIDAD AND TOBAGO","curr_name" => "Trinidad and Tobago Dollar","curr_number" => "780"),
							"TWD" => array("country" => "TAIWAN, PROVINCE OF CHINA","curr_name" => "New Taiwan Dollar","curr_number" => "901"),
							"TZS" => array("country" => "TANZANIA, UNITED REPUBLIC OF","curr_name" => "Tanzanian Shilling","curr_number" => "834"),
							"UAH" => array("country" => "UKRAINE","curr_name" => "Hryvnia","curr_number" => "980"),
							"UGX" => array("country" => "UGANDA","curr_name" => "Uganda Shilling","curr_number" => "800"),
							"USD" => array("country" => "AMERICAN SAMOA","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "BRITISH INDIAN OCEAN TERRITORY","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "ECUADOR","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "EL SALVADOR","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "GUAM","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "HAITI","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "MARSHALL ISLANDS","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "MICRONESIA, FEDERATED STATES OF","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "NORTHERN MARIANA ISLANDS","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "PALAU","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "PANAMA","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "PUERTO RICO","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "TIMOR-LESTE","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "TURKS AND CAICOS ISLANDS","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "UNITED STATES MINOR OUTLYING ISLANDS","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "UNITED STATES","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "VIRGIN ISLANDS (BRITISH)","curr_name" => "US Dollar","curr_number" => "840"),
							"USD" => array("country" => "VIRGIN ISLANDS (U.S.)","curr_name" => "US Dollar","curr_number" => "840"),
							"USN" => array("country" => "UNITED STATES","curr_name" => "US Dollar (Next day)","curr_number" => "997"),
							"USS" => array("country" => "UNITED STATES","curr_name" => "US Dollar (Same day)","curr_number" => "998"),
							"UYI" => array("country" => "URUGUAY","curr_name" => "Uruguay Peso en Unidades Indexadas","curr_number" => "940"),
							"UYU" => array("country" => "URUGUAY","curr_name" => "Peso Uruguayo","curr_number" => "858"),
							"UZS" => array("country" => "UZBEKISTAN","curr_name" => "Uzbekistan Sum","curr_number" => "860"),
							"VEF" => array("country" => "VENEZUELA","curr_name" => "Bolivar Fuerte","curr_number" => "937"),
							"VND" => array("country" => "VIET NAM","curr_name" => "Dong","curr_number" => "704"),
							"VUV" => array("country" => "VANUATU","curr_name" => "Vatu","curr_number" => "548"),
							"WST" => array("country" => "SAMOA","curr_name" => "Tala","curr_number" => "882"),
							"XAF" => array("country" => "CAMEROON","curr_name" => "CFA Franc BEAC ","curr_number" => "950"),
							"XAF" => array("country" => "CENTRAL AFRICAN REPUBLIC","curr_name" => "CFA Franc BEAC ","curr_number" => "950"),
							"XAF" => array("country" => "CHAD","curr_name" => "CFA Franc BEAC ","curr_number" => "950"),
							"XAF" => array("country" => "CONGO","curr_name" => "CFA Franc BEAC ","curr_number" => "950"),
							"XAF" => array("country" => "EQUATORIAL GUINEA","curr_name" => "CFA Franc BEAC ","curr_number" => "950"),
							"XAF" => array("country" => "GABON","curr_name" => "CFA Franc BEAC ","curr_number" => "950"),
							"XCD" => array("country" => "ANGUILLA","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XCD" => array("country" => "ANTIGUA AND BARBUDA","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XCD" => array("country" => "DOMINICA","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XCD" => array("country" => "GRENADA","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XCD" => array("country" => "MONTSERRAT","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XCD" => array("country" => "SAINT KITTS AND NEVIS","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XCD" => array("country" => "SAINT LUCIA","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XCD" => array("country" => "SAINT VINCENT AND THE GRENADINES","curr_name" => "East Caribbean Dollar","curr_number" => "951"),
							"XOF" => array("country" => "BENIN","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XOF" => array("country" => "BURKINA FASO","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XOF" => array("country" => "CÔTE D'IVOIRE","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XOF" => array("country" => "GUINEA-BISSAU","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XOF" => array("country" => "MALI","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XOF" => array("country" => "NIGER","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XOF" => array("country" => "SENEGAL","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XOF" => array("country" => "TOGO","curr_name" => "CFA Franc BCEAO ","curr_number" => "952"),
							"XPF" => array("country" => "FRENCH POLYNESIA","curr_name" => "CFP Franc","curr_number" => "953"),
							"XPF" => array("country" => "NEW CALEDONIA","curr_name" => "CFP Franc","curr_number" => "953"),
							"XPF" => array("country" => "WALLIS AND FUTUNA","curr_name" => "CFP Franc","curr_number" => "953"),
							"YER" => array("country" => "YEMEN","curr_name" => "Yemeni Rial","curr_number" => "886"),
							"ZAR" => array("country" => "LESOTHO","curr_name" => "Rand","curr_number" => "710"),
							"ZAR" => array("country" => "NAMIBIA","curr_name" => "Rand","curr_number" => "710"),
							"ZAR" => array("country" => "SOUTH AFRICA","curr_name" => "Rand","curr_number" => "710"),
							"ZMK" => array("country" => "ZAMBIA","curr_name" => "Zambian Kwacha","curr_number" => "894"),
							"ZWR" => array("country" => "ZIMBABWE","curr_name" => "Zimbabwe Dollar","curr_number" => "935"),
					);


?>