<?php
/**

	Uretici..........: Moka 
	Yazılımın Adı....: Moka_Payment // moka.com için Magento Tahsilat Modülü
	Geliştiren.......: Hidayet Ok <hidayet@grinet.com.tr>
	Web..............: https://www.moka.com/

	/// Yasal Uyarı /////////////////////////////////////////////////////////////////////////

	Tüm hakları MOKA ÖDEME KURULUŞU A.Ş.'ne aittir.

*/
?>
<?php 

	$turkpay = Mage::getModel('Moka_Payment_Model_Grinet');
	$ip=$turkpay->get_remote_ip();
	
?>
<style type="text/css">
	.license_box{
			border:lightgrey 1px solid;
			background:#F0F0F0;
			color:gray;
			padding:15px;
		}

	.license_box h3{
			color:orange;
			font-size:14px;
		}
	.ip{
			color:brown;
			font-size:14px;
		}
</style>
<div class="license_box">
    <h3><?php echo $ip;?></h3>
	Ödeme sistemi sağlayıcıları sizden IP adresinizi isterse bu ip adresini veriniz. 
</div>
<p>