<?php
/**

	Uretici..........: Moka 
	Yazılımın Adı....: Moka_Payment // moka.com için Magento Tahsilat Modülü
	Geliştiren.......: Hidayet Ok <hidayet@grinet.com.tr>
	Web..............: https://www.moka.com/

	/// Yasal Uyarı /////////////////////////////////////////////////////////////////////////

	Tüm hakları MOKA ÖDEME KURULUŞU A.Ş.'ne aittir.

*/
?><?php

	echo '<img src="'.$this->getSkinUrl('images/Grinet_moka/loading2.gif').'" border="0" hspace="10" vspace="10" align="left" alt="'.__('Lütfen bekleyiniz...').'"><br><br>';
	echo "<h2>".__("Bankanızın sistemine yönlendiriliyorsunuz...")."</h2>";
		
